(() => {
const TIER_ORDER = ['common', 'rare', 'epic', 'cursed', 'legendary'];

const PERKS = [
  { id:'sw_c1',  tier:'common', name:'Slim I',       icon:'🪶', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'sw_c2',  tier:'common', name:'Slim II',      icon:'🪶', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'qs_c1',  tier:'common', name:'Lean I',       icon:'🌿', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'qs_c2',  tier:'common', name:'Lean II',      icon:'🌿', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'lf_c1',  tier:'common', name:'Trim I',       icon:'✂️', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'nb_c1',  tier:'common', name:'Compact I',    icon:'🔽', color:'#38d4a8', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'nb_c2',  tier:'common', name:'Compact II',   icon:'🔽', color:'#38d4a8', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'da_c1',  tier:'common', name:'Shrink I',     icon:'📉', color:'#38d4a8', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'da_c2',  tier:'common', name:'Shrink II',    icon:'📉', color:'#38d4a8', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'ru_c1',  tier:'common', name:'Compress I',   icon:'🗜️', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'fl_c1',  tier:'common', name:'Compress II',  icon:'🗜️', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'hu_c1',  tier:'common', name:'Minimize I',   icon:'⬇️', color:'#4ecca3', shadow:'#1a6650', effects:{ shrink:1 }, desc:'-1 body segment instantly' },
  { id:'ap_c1',  tier:'common', name:'Appetite I',    icon:'🍎', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'ap_c2',  tier:'common', name:'Appetite II',   icon:'🍎', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'sn_c1',  tier:'common', name:'Snacker',       icon:'🍬', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'gl_c1',  tier:'common', name:'Glutton I',     icon:'🍕', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'hn_c1',  tier:'common', name:'Hungry I',      icon:'🦁', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'lb_c1',  tier:'common', name:'Lucky Bite I',  icon:'🍀', color:'#ff8c00', shadow:'#6a3800', effects:{ doubleScoreChance:5  }, desc:'5% chance to double score' },
  { id:'lb_c2',  tier:'common', name:'Lucky Bite II', icon:'🍀', color:'#ff8c00', shadow:'#6a3800', effects:{ doubleScoreChance:5  }, desc:'5% chance to double score' },
  { id:'br_c1',  tier:'common', name:'Bonus Round',   icon:'🎰', color:'#ff8c00', shadow:'#6a3800', effects:{ doubleScoreChance:6  }, desc:'6% chance to double score' },
  { id:'st_c1',  tier:'common', name:'Sweet Tooth',   icon:'🍩', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'ef_c1',  tier:'common', name:'Efficiency I',  icon:'💡', color:'#ffd700', shadow:'#6a5800', effects:{ bonusScore:1 }, desc:'+1 score per food' },
  { id:'gt_c1',  tier:'common', name:'Gold Tooth',    icon:'🦷', color:'#ffd700', shadow:'#6a5800', effects:{ doubleScoreChance:7  }, desc:'7% chance to double score' },
  { id:'ct_c1',  tier:'common', name:'Combo Time I',  icon:'🔥', color:'#ff6b35', shadow:'#6a2800', effects:{ comboWindow:200 }, desc:'+0.2s combo window' },
  { id:'ct_c2',  tier:'common', name:'Combo Time II', icon:'🔥', color:'#ff6b35', shadow:'#6a2800', effects:{ comboWindow:300 }, desc:'+0.3s combo window' },
  { id:'hs_c1',  tier:'common', name:'Hot Streak I',  icon:'🌶️', color:'#ff4500', shadow:'#6a1500', effects:{ comboWindow:250 }, desc:'+0.25s combo window' },
  { id:'mo_c1',  tier:'common', name:'Momentum I',    icon:'🎯', color:'#ff6b35', shadow:'#6a2800', effects:{ comboMax:1   }, desc:'+1 max combo multiplier' },
  { id:'ch_c1',  tier:'common', name:'Chain I',       icon:'⛓️', color:'#ff6b35', shadow:'#6a2800', effects:{ comboWindow:200 }, desc:'+0.2s combo window' },
  { id:'rf_c1',  tier:'common', name:'Rapid Fire I',  icon:'🏹', color:'#ff8c00', shadow:'#6a3800', effects:{ comboWindow:300 }, desc:'+0.3s combo window' },
  { id:'or_c1',  tier:'common', name:'On a Roll I',   icon:'🎳', color:'#ff6b35', shadow:'#6a2800', effects:{ comboWindow:400 }, desc:'+0.4s combo window' },
  { id:'fm_c1',  tier:'common', name:'Flame I',       icon:'🕯️', color:'#ff4500', shadow:'#6a1500', effects:{ comboMax:1   }, desc:'+1 max combo multiplier' },
  { id:'fw_c1',  tier:'common', name:'Flow I',        icon:'🌊', color:'#00bfff', shadow:'#004488', effects:{ comboWindow:200 }, desc:'+0.2s combo window' },
  { id:'cb_c1',  tier:'common', name:'Combo Boost I', icon:'✨', color:'#ffd700', shadow:'#6a5800', effects:{ comboWindow:350 }, desc:'+0.35s combo window' },
  { id:'ts_c1',  tier:'common', name:'Tough Skin I',  icon:'🛡️', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'th_c1',  tier:'common', name:'Thick Hide I',  icon:'🦏', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'ww_c1',  tier:'common', name:'Wall Walker I', icon:'👻', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:1 }, desc:'+1 wall pass' },
  { id:'ps_c1',  tier:'common', name:'Phase Step I',  icon:'🌀', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:1 }, desc:'+1 wall pass' },
  { id:'gr_c1',  tier:'common', name:'Grit I',        icon:'💪', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'ba_c1',  tier:'common', name:'Barrier I',     icon:'🔰', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'en_c1',  tier:'common', name:'Endure I',      icon:'🏋️', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'ph_c1',  tier:'common', name:'Phase I',       icon:'💫', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:1 }, desc:'+1 wall pass' },
  { id:'so_c1',  tier:'common', name:'Shrug Off I',   icon:'🥊', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'ss_c1',  tier:'common', name:'Side Step I',   icon:'💃', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:1 }, desc:'+1 wall pass' },
  { id:'iw_c1',  tier:'common', name:'Iron Will I',   icon:'⚙️', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:1   }, desc:'Survive 1 self-collision' },
  { id:'bk_c1',  tier:'common', name:'Breaker I',     icon:'🔨', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:1 }, desc:'+1 wall pass' },
  { id:'ef_f1',  tier:'common', name:'Extra Food I',      icon:'🍇', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'ab_c1',  tier:'common', name:'Abundance I',       icon:'🌽', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'fg_c1',  tier:'common', name:'Fertile Ground I',  icon:'🌱', color:'#66ff88', shadow:'#1a5030', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'cr_c1',  tier:'common', name:'Crop I',            icon:'🌾', color:'#ffd700', shadow:'#6a5800', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'gd_c1',  tier:'common', name:'Gardens I',         icon:'🌷', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'hv_c1',  tier:'common', name:'Harvest I',         icon:'🍂', color:'#ff8c00', shadow:'#6a3800', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'pl_c1',  tier:'common', name:'Plenty I',          icon:'🍱', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'xs_c1',  tier:'common', name:'Extra Serving I',   icon:'🍽️', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:1 }, desc:'+1 food spawns on board' },
  { id:'ql_c1',  tier:'common', name:'Quick Learner I', icon:'📚', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'st_x1',  tier:'common', name:'Study I',         icon:'🎓', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'sm_c1',  tier:'common', name:'Sharp Mind I',    icon:'🧠', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'wi_c1',  tier:'common', name:'Wisdom I',        icon:'🦉', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'sc_c1',  tier:'common', name:'Scholar I',       icon:'📖', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'gr_x1',  tier:'common', name:'Growth I',        icon:'🌿', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:1 }, desc:'+1 XP per food eaten' },
  { id:'sw_r1',  tier:'rare', name:'Slim III',         icon:'🪶', color:'#4d9fff', shadow:'#1a4080', effects:{ shrink:2 }, desc:'-2 body segments instantly' },
  { id:'sw_r2',  tier:'rare', name:'Slim IV',          icon:'🪶', color:'#4d9fff', shadow:'#1a4080', effects:{ shrink:3 }, desc:'-3 body segments instantly' },
  { id:'sw_r3',  tier:'rare', name:'Slim V',           icon:'🪶', color:'#4d9fff', shadow:'#1a4080', effects:{ shrink:3 }, desc:'-3 body segments instantly' },
  { id:'bl_r1',  tier:'rare', name:'Blitz I',          icon:'⚡', color:'#00bfff', shadow:'#004488', effects:{ burstChance:0.15 }, desc:'15% chance of speed burst on eat' },
  { id:'bl_r2',  tier:'rare', name:'Blitz Surge',      icon:'⚡', color:'#00bfff', shadow:'#004488', effects:{ burstDuration:1000 }, desc:'+1s speed burst duration' },
  { id:'ap_r1',  tier:'rare', name:'Appetite III',     icon:'🍎', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:2 }, desc:'+2 score per food' },
  { id:'ap_r2',  tier:'rare', name:'Appetite IV',      icon:'🍎', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:3 }, desc:'+3 score per food' },
  { id:'db_r1',  tier:'rare', name:'Double Down',      icon:'💎', color:'#ff8c00', shadow:'#6a3800', effects:{ doubleScoreChance:18 }, desc:'18% chance to double score' },
  { id:'tr_r1',  tier:'rare', name:'Triple Threat',    icon:'🎯', color:'#ff6b35', shadow:'#6a2800', effects:{ tripleScoreChance:12 }, desc:'12% chance to triple score' },
  { id:'gl_r1',  tier:'rare', name:'Glutton II',       icon:'🍕', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:2 }, desc:'+2 score per food' },
  { id:'hn_r1',  tier:'rare', name:'Hungry II',        icon:'🦁', color:'#e94560', shadow:'#6a1025', effects:{ bonusScore:2 }, desc:'+2 score per food' },
  { id:'gd_r1',  tier:'rare', name:'Gold Fever',       icon:'🥇', color:'#ffd700', shadow:'#6a5800', effects:{ bonusScore:3, doubleScoreChance:8 }, desc:'+3 score · 8% chance to double score' },
  { id:'ct_r1',  tier:'rare', name:'Combo Time III',   icon:'🔥', color:'#ff4500', shadow:'#6a1500', effects:{ comboWindow:800  }, desc:'+0.8s combo window' },
  { id:'ct_r2',  tier:'rare', name:'Combo Time IV',    icon:'🔥', color:'#ff4500', shadow:'#6a1500', effects:{ comboWindow:1000 }, desc:'+1s combo window' },
  { id:'cm_r1',  tier:'rare', name:'Combo Master',     icon:'⭐', color:'#ffd700', shadow:'#6a5800', effects:{ comboMax:2 }, desc:'+2 max combo multiplier' },
  { id:'nr_r1',  tier:'rare', name:'Wall Rhythm',      icon:'🌊', color:'#00bfff', shadow:'#004488', effects:{ comboNoReset:true }, desc:'Wall passes don\'t break combo timer' },
  { id:'hs_r1',  tier:'rare', name:'Hot Streak II',    icon:'🌶️', color:'#ff4500', shadow:'#6a1500', effects:{ comboWindow:700, comboMax:1 }, desc:'+0.7s window · +1 max combo' },
  { id:'ts_r1',  tier:'rare', name:'Tough Skin II',    icon:'🛡️', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:2   }, desc:'Survive 2 self-collisions' },
  { id:'ts_r2',  tier:'rare', name:'Tough Skin III',   icon:'🛡️', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:3   }, desc:'Survive 3 self-collisions' },
  { id:'ww_r1',  tier:'rare', name:'Wall Walker II',   icon:'👻', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:2 }, desc:'+2 wall passes' },
  { id:'ww_r2',  tier:'rare', name:'Wall Walker III',  icon:'👻', color:'#bf7fff', shadow:'#4a2070', effects:{ wallPasses:3 }, desc:'+3 wall passes' },
  { id:'sc_r1',  tier:'rare', name:'Second Chance',    icon:'🔄', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:2, wallPasses:2 }, desc:'+2 self-hits · +2 wall passes' },
  { id:'gr_r1',  tier:'rare', name:'Grit II',          icon:'💪', color:'#66ff88', shadow:'#1a5030', effects:{ selfHits:3   }, desc:'Survive 3 self-collisions' },
  { id:'ex_r1',  tier:'rare', name:'Bigger World I',   icon:'🗺️', color:'#cc44ff', shadow:'#6600aa', effects:{ boardExpand:{dx:2,dy:2} }, desc:'Grid grows by +2×2' },
  { id:'ex_r2',  tier:'rare', name:'Bigger World II',  icon:'🗺️', color:'#cc44ff', shadow:'#6600aa', effects:{ boardExpand:{dx:4,dy:4} }, desc:'Grid grows by +4×4' },
  { id:'ef_r1',  tier:'rare', name:'Extra Food II',    icon:'🍇', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:2 }, desc:'+2 food spawns on board' },
  { id:'ef_r2',  tier:'rare', name:'Extra Food III',   icon:'🍇', color:'#ff69b4', shadow:'#6a1040', effects:{ extraFood:3 }, desc:'+3 food spawns on board' },
  { id:'ql_r1',  tier:'rare', name:'Quick Learner II', icon:'📚', color:'#4d9fff', shadow:'#1a4080', effects:{ bonusXP:2 }, desc:'+2 XP per food eaten' },
  { id:'xr_r1',  tier:'rare', name:'XP Discount I',   icon:'📉', color:'#4d9fff', shadow:'#1a4080', effects:{ xpReqMult:0.90 }, desc:'-10% XP needed for levels' },
  { id:'xr_r2',  tier:'rare', name:'XP Discount II',  icon:'📉', color:'#4d9fff', shadow:'#1a4080', effects:{ xpReqMult:0.90 }, desc:'-10% XP needed for levels' },
  { id:'sg_e1',  tier:'epic', name:'Singularity',    icon:'🌌', color:'#cc44ff', shadow:'#6600aa', effects:{ boardExpand:{dx:8,dy:8}, extraFood:2 }, desc:'Grid +8×8 · +2 food on board' },
  { id:'ov_e1',  tier:'epic', name:'Omnivore',       icon:'🐲', color:'#cc44ff', shadow:'#6600aa', effects:{ bonusScore:8 }, desc:'+8 score per food eaten' },
  { id:'ic_e1',  tier:'epic', name:'Immortal Coil',  icon:'♾️', color:'#cc44ff', shadow:'#6600aa', effects:{ selfHits:5, wallPasses:5 }, desc:'+5 self-hit shield · +5 wall passes' },
  { id:'hb_e1',  tier:'epic', name:'Hyperblitz',     icon:'🌩️', color:'#00bfff', shadow:'#004488', effects:{ burstChance:0.50, burstDuration:3000, burstScoreMult:2 }, desc:'50% burst chance · +3s duration · ×3 score in burst' },
  { id:'ih_e1',  tier:'epic', name:'Infinite Hunger',icon:'🍄', color:'#cc44ff', shadow:'#6600aa', effects:{ extraFood:5 }, desc:'+5 food spawns on board' },
  { id:'fs_e1',  tier:'epic', name:'Flow State',     icon:'🌀', color:'#cc44ff', shadow:'#6600aa', effects:{ comboWindow:5000, comboNoReset:true }, desc:'+5s combo window, wall passes don\'t break combo timer' },
  { id:'mo_e1',  tier:'epic', name:'Minimize',       icon:'⬇️', color:'#00bfff', shadow:'#004488', effects:{ shrink:6 }, desc:'-6 body segments instantly' },
  { id:'xs_e1',  tier:'epic', name:'XP Surge',       icon:'🚀', color:'#cc44ff', shadow:'#6600aa', effects:{ xpReqMult:0.50 }, desc:'Halve current and future XP requirements' },
  { id:'bw_e1',  tier:'epic', name:'Big World',      icon:'🌍', color:'#cc44ff', shadow:'#6600aa', effects:{ boardExpand:{dx:12,dy:12}, extraFood:4 }, desc:'Grid +12×12 · +4 food on board' },
  { id:'bl_cu1', tier:'cursed', name:'Blood Pact',      icon:'🩸', color:'#ff4466', shadow:'#660022', effects:{ bonusScore:15, extraGrowth:3 }, desc:'+15 score per food · ⚠ grow 3 extra segments per lvl' },
  { id:'in_cu1', tier:'cursed', name:'Insatiable',      icon:'🦈', color:'#ff4466', shadow:'#660022', effects:{ extraFood:8, bonusScore:8, extraGrowth:2 }, desc:'+8 food · +8 score · ⚠ grow 2 extra per lvl' },
  { id:'fr_cu1', tier:'cursed', name:'Frenzy',          icon:'💀', color:'#ff4466', shadow:'#660022', effects:{ burstScoreMult:5, forcedBurst:true }, desc:'×6 score in burst · ⚠ permanently at burst speed' },
  { id:'dm_cu1', tier:'cursed', name:'Damnation',       icon:'😈', color:'#ff4466', shadow:'#660022', effects:{ selfHits:12, wallPasses:12, wallDamage:3 }, desc:'+12 shield & wall passes · ⚠ each wall pass costs 3 shields' },
  { id:'gs_cu1', tier:'cursed', name:'Gluttony\'s Sin', icon:'🌋', color:'#ff4466', shadow:'#660022', effects:{ boardExpand:{dx:14,dy:14}, extraFood:10, extraGrowth:4 }, desc:'Grid +14×14 · +10 food · ⚠ grow 4 extra per lvl' },
  { id:'wc_cu1', tier:'cursed', name:'Warped Coil',     icon:'🌀', color:'#ff4466', shadow:'#660022', effects:{ wallPasses:25, comboWindow:8000, comboNoReset:true, wallDamage:2 }, desc:'+25 wall passes · +8s combo · ⚠ each pass costs 2 shields' },
  { id:'sc_cu1', tier:'cursed', name:'Soul Crusher',    icon:'⚠️', color:'#ff4466', shadow:'#660022', effects:{ bonusScore:25, xpReqMult:0.15, forcedBurst:true, extraGrowth:5 }, desc:'+25 score · -85% XP req · ⚠ burst speed + grow 5 extra per lvl' },
  { id:'oc_cu1', tier:'cursed', name:'Omega Coil',      icon:'🔱', color:'#ff4466', shadow:'#660022', effects:{ shrink:8, bonusScore:10, selfHits:5, extraGrowth:10 }, desc:'-8 size now · +10 score · +5 shield · ⚠ grow 10 extra per lvl' },
  { id:'as_e1',  tier:'legendary', name:'Ascendant', icon:'👑', color:'#ffd700', shadow:'#6a5800', effects:{ bonusScore:5, shrink:2, selfHits:3, wallPasses:3, comboMax:3, extraFood:2 }, desc:'+5 score · -2 size · +3 shield · +3 walls · +3 max combo · +2 food' },
];

const PERK_MAP = Object.fromEntries(PERKS.map(perk => [perk.id, perk]));

window.SnakePerks = {
  TIER_ORDER,
  PERKS,
  PERK_MAP,
};
})();
